### ISSUE TITLE
Not working in the latest Sketch Beta 3.4

### ISSUE THREAD

**Issue by mrrocks** [t32k/material-design-color-palette#4]

**Comment by energy7** [comment]
Not working in Sketch 3.3.3 either.

**Comment by t32k** [comment]
:cry:

**Comment by jwill** [comment]
Unable to duplicate error. Works fine in 3.3.3 for me.

**Comment by hpoul** [comment]
Not working for me either. It just creates an empty rectangle.

Sketch 3.3.3, Mac OSX 10.11

Console log shows:

```
17/10/15 11:34:55,629 Sketch[1025]: Exception: TypeError: colorBlock.embedInShapeGroup is not a function. (In 'colorBlock.embedInShapeGroup()', 'colorBlock.embedInShapeGroup' is undefined)
17/10/15 11:34:55,629 Swatch (Sketch Plugin)[1025]: TypeError: colorBlock.embedInShapeGroup is not a function. (In 'colorBlock.embedInShapeGroup()', 'colorBlock.embedInShapeGroup' is undefined)
line: 162
sourceURL: /Users/herbert/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Material Design Color Palette Sketch Plugin/Swatch.sketchplugin
column: 44
```

**Comment by t32k** [comment]
Hi, guys. I fixed and updated my plugin to v2.2.0. Please reinstall the plugin of this version.
You can confirm plugin version at sketchpack.json.

**Comment by t32k** [comment]
I supported v3.4 new file format, so please try v3.0.0!
https://github.com/t32k/material-design-color-palette/releases
